# Generated by Django 4.2.10 on 2025-11-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EGA_KPIS_PROD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recid', models.IntegerField(null=True)),
                ('maquina', models.IntegerField(null=True)),
                ('registro', models.DateTimeField(null=True)),
                ('os', models.IntegerField(null=True)),
                ('produto', models.IntegerField(null=True)),
                ('operacao', models.IntegerField(null=True)),
                ('molde', models.IntegerField(null=True)),
                ('ttotal', models.IntegerField(null=True)),
                ('sec_total', models.IntegerField(null=True)),
                ('tdisp', models.IntegerField(null=True)),
                ('sec_disp', models.IntegerField(null=True)),
                ('tprod', models.IntegerField(null=True)),
                ('sec_prod', models.IntegerField(null=True)),
                ('qtde_std', models.IntegerField(null=True)),
                ('qtde_real', models.IntegerField(null=True)),
                ('qtde_boas', models.IntegerField(null=True)),
                ('teep', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('oee', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('disp', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('perf', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('qualidade', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
